name: Deploy feature pre-check

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select env
        required: true
        type: choice
        options:
          - test
          - prod

jobs:
  job1:
    environment: "${{ inputs.env }}-1"
    name: Prepare job environment
    runs-on: ubuntu-latest
    steps:
      - name: Get RUNNER_LABEL
        id: get-runner-label
        run: |
          echo "step1"
