name: Deploy feature pre-check

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select env
        required: true
        type: choice
        options:
          - test
          - prod

jobs:
  job1:
    environment: "${{ inputs.env }}-1"
    name: Prepare job environment
    runs-on: ubuntu-latest
    steps:
      - name: Get RUNNER_LABEL
        id: get-runner-label
        run: |
          echo "step1"

  deployment-approval:
    environment: "${{ inputs.env }}"
    if: ${{ inputs.env == 'test' && github.ref != 'refs/heads/main' }}
    needs:
      - job1
    name: Deployment approval from fature branch
    runs-on: ubuntu-latest
    steps:
      - name: Approval step
        run: echo "Deployment from feature branch approved"
        
  job3:
    environment: "${{ inputs.env }}"
    if: ${{ 
            always() && (needs.job1.result == 'success') && 
            (needs.deployment-approval.result == 'success' || needs.deployment-approval.result == 'skipped') 
        }}
    needs:
      - job1
      - deployment-approval
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - name: Approval step
        id: step-approval-id
        run: echo "approval"
