name: Deploy domains

on:
  workflow_dispatch:
    inputs:
      env:
        description: Select env
        required: true
        type: choice
        options:
          - test
          - prod
  workflow_call:
    inputs:
      env:
        description: Region
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    strategy:
      matrix:
        domain: ["sand", "sand2", "sand3", "sand4"]
    uses: ./.github/workflows/test.yml
    secrets: inherit
    permissions:
      actions: read
      contents: write
    with:
      domain: ${{ matrix.domain }}
      env: ${{ inputs.env }}
